commitFormat: angular
title: "windhager mes-infinity client-go"
branch:
  main: release
changelog:
  printAll: false
release: 'github'
assets:
  - name: -
    compress: true
github:
  repo: "windhager-mes-infinity-client-go"
  user: "lukibahr"
