# .xplicit.yaml file gives me hints about explicit stuff i do in various projects
xplicit:
  case: 
    - name: "api client implementation in go"
      description: ""
    - name: "digest auth in golang"
      description: ""